name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16.5.0

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: dependencies-16-5-${{ hashFiles('./package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --no-audit --no-optional

    - name: Build
      run: npm run build

    - name: Git Config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Git Commit & Push
      run: |
        git add dist
        git commit -m "GitHub Actions Auto-Deploy"
        git push origin master

